name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on ${{ matrix.runtime }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [bun]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - name: Lint
        run: bun lint

      - name: Test
        run: bun test

      - name: Build
        run: bun run build
